### ISSUE TITLE
Error to get PugViewInstance object with a certain CID entry

### ISSUE THREAD

**Issue by elian-stz** [selcukorkmaz/PubChemR#9]
Hello, thank you for developping this package. I think I encountered a bug with `get_pug_view()`

Here's the code snippet:

```
PubChemR::get_pug_view(identifier=6321405, annotation="data")
```

The error message I get is `Error in file(con, "r") : invalid 'description' argument`. This error does not appear for other CIDs such as 632140. This is the only buggy CID that I've found so far.

**Comment by dncR** [comment]
Hello @elian-stz, 

Thanks for the bug report. We have experienced several unexpected errors, which are mostly related to PubChem API, in development state of the package. Your report also seems to be another API related issue. Nonetheless, we will check it if it is an issue which can be credited to our package or not. 

Best,

Dincer.

**Comment by dncR** [comment]
Dear @elian-stz,

The PubChemR package benefits from `GET` function of **httr** package to retrieve data using the URL of PubChem requests. Two example requests using compound IDs 6321405 and 6321405 are executed over the URLs

- [1] https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/6321405/JSON
- [2] https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/632140/JSON

It seem both URLs are valid and data can be retrieved through a web browser. However, the `get_pug_view` function returns error for URL [1]. You can try it by yourself by running

```
res1 <- httr::GET("https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/632140/JSON")
httr::content(res1)

res2 <- httr::GET("https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/6321405/JSON")
httr::content(res2)

# Content is not NA here.
rawToChar(res2$content)
```

It seems to be a bug which might be related to PubChem API or `GET function` of **httr** package, returning NA even though it retrieves the URL content as raw data in `res2$content`. We will dive into more details by running codes line by line to fix it. At this point, I will close this issue because the primary reason of this error is not the PubChemR package. Perhaps, we can overcome this issue by pulling data using alternative file format such as XML. Please follow further updates and check NEWS if we will be able to fix this issue in forthcoming releases.

Best,
